// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BlobstoreAzure extends pulumi.CustomResource {
    /**
     * Get an existing BlobstoreAzure resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BlobstoreAzureState, opts?: pulumi.CustomResourceOptions): BlobstoreAzure {
        return new BlobstoreAzure(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/blobstoreAzure:BlobstoreAzure';

    /**
     * Returns true if the given object is an instance of BlobstoreAzure.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BlobstoreAzure {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BlobstoreAzure.__pulumiType;
    }

    /**
     * Count of blobs
     */
    public /*out*/ readonly blobCount!: pulumi.Output<number>;
    /**
     * The Azure specific configuration details for the Azure object that'll contain the blob store
     */
    public readonly bucketConfiguration!: pulumi.Output<outputs.BlobstoreAzureBucketConfiguration>;
    /**
     * Blobstore name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Soft quota of the blobstore
     */
    public readonly softQuota!: pulumi.Output<outputs.BlobstoreAzureSoftQuota | undefined>;
    /**
     * The total size of the blobstore in Bytes
     */
    public /*out*/ readonly totalSizeInBytes!: pulumi.Output<number>;

    /**
     * Create a BlobstoreAzure resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BlobstoreAzureArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BlobstoreAzureArgs | BlobstoreAzureState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BlobstoreAzureState | undefined;
            resourceInputs["blobCount"] = state ? state.blobCount : undefined;
            resourceInputs["bucketConfiguration"] = state ? state.bucketConfiguration : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["softQuota"] = state ? state.softQuota : undefined;
            resourceInputs["totalSizeInBytes"] = state ? state.totalSizeInBytes : undefined;
        } else {
            const args = argsOrState as BlobstoreAzureArgs | undefined;
            if ((!args || args.bucketConfiguration === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bucketConfiguration'");
            }
            resourceInputs["bucketConfiguration"] = args ? args.bucketConfiguration : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["softQuota"] = args ? args.softQuota : undefined;
            resourceInputs["blobCount"] = undefined /*out*/;
            resourceInputs["totalSizeInBytes"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BlobstoreAzure.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BlobstoreAzure resources.
 */
export interface BlobstoreAzureState {
    /**
     * Count of blobs
     */
    blobCount?: pulumi.Input<number>;
    /**
     * The Azure specific configuration details for the Azure object that'll contain the blob store
     */
    bucketConfiguration?: pulumi.Input<inputs.BlobstoreAzureBucketConfiguration>;
    /**
     * Blobstore name
     */
    name?: pulumi.Input<string>;
    /**
     * Soft quota of the blobstore
     */
    softQuota?: pulumi.Input<inputs.BlobstoreAzureSoftQuota>;
    /**
     * The total size of the blobstore in Bytes
     */
    totalSizeInBytes?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a BlobstoreAzure resource.
 */
export interface BlobstoreAzureArgs {
    /**
     * The Azure specific configuration details for the Azure object that'll contain the blob store
     */
    bucketConfiguration: pulumi.Input<inputs.BlobstoreAzureBucketConfiguration>;
    /**
     * Blobstore name
     */
    name?: pulumi.Input<string>;
    /**
     * Soft quota of the blobstore
     */
    softQuota?: pulumi.Input<inputs.BlobstoreAzureSoftQuota>;
}
