// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBlobstoreGroup(args: GetBlobstoreGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetBlobstoreGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getBlobstoreGroup:getBlobstoreGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBlobstoreGroup.
 */
export interface GetBlobstoreGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getBlobstoreGroup.
 */
export interface GetBlobstoreGroupResult {
    readonly availableSpaceInBytes: number;
    readonly blobCount: number;
    readonly fillPolicy: string;
    readonly id: string;
    readonly members: string[];
    readonly name: string;
    readonly softQuotas: outputs.GetBlobstoreGroupSoftQuota[];
    readonly totalSizeInBytes: number;
}
export function getBlobstoreGroupOutput(args: GetBlobstoreGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBlobstoreGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getBlobstoreGroup:getBlobstoreGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBlobstoreGroup.
 */
export interface GetBlobstoreGroupOutputArgs {
    name: pulumi.Input<string>;
}
