// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBlobstoreList(opts?: pulumi.InvokeOptions): Promise<GetBlobstoreListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getBlobstoreList:getBlobstoreList", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getBlobstoreList.
 */
export interface GetBlobstoreListResult {
    readonly id: string;
    readonly items: outputs.GetBlobstoreListItem[];
}
export function getBlobstoreListOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBlobstoreListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getBlobstoreList:getBlobstoreList", {
    }, opts, utilities.getPackage());
}
