// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBlobstoreAzure(args: GetBlobstoreAzureArgs, opts?: pulumi.InvokeOptions): Promise<GetBlobstoreAzureResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getBlobstoreAzure:getBlobstoreAzure", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBlobstoreAzure.
 */
export interface GetBlobstoreAzureArgs {
    name: string;
}

/**
 * A collection of values returned by getBlobstoreAzure.
 */
export interface GetBlobstoreAzureResult {
    readonly blobCount: number;
    readonly bucketConfigurations: outputs.GetBlobstoreAzureBucketConfiguration[];
    readonly id: string;
    readonly name: string;
    readonly softQuotas: outputs.GetBlobstoreAzureSoftQuota[];
    readonly totalSizeInBytes: number;
}
export function getBlobstoreAzureOutput(args: GetBlobstoreAzureOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBlobstoreAzureResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getBlobstoreAzure:getBlobstoreAzure", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBlobstoreAzure.
 */
export interface GetBlobstoreAzureOutputArgs {
    name: pulumi.Input<string>;
}
