// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBlobstoreS3(args: GetBlobstoreS3Args, opts?: pulumi.InvokeOptions): Promise<GetBlobstoreS3Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getBlobstoreS3:getBlobstoreS3", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBlobstoreS3.
 */
export interface GetBlobstoreS3Args {
    name: string;
}

/**
 * A collection of values returned by getBlobstoreS3.
 */
export interface GetBlobstoreS3Result {
    readonly blobCount: number;
    readonly bucketConfigurations: outputs.GetBlobstoreS3BucketConfiguration[];
    readonly id: string;
    readonly name: string;
    readonly softQuotas: outputs.GetBlobstoreS3SoftQuota[];
    readonly totalSizeInBytes: number;
}
export function getBlobstoreS3Output(args: GetBlobstoreS3OutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBlobstoreS3Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getBlobstoreS3:getBlobstoreS3", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getBlobstoreS3.
 */
export interface GetBlobstoreS3OutputArgs {
    name: pulumi.Input<string>;
}
