// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMailConfig(opts?: pulumi.InvokeOptions): Promise<GetMailConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getMailConfig:getMailConfig", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getMailConfig.
 */
export interface GetMailConfigResult {
    readonly enabled: boolean;
    readonly fromAddress: string;
    readonly host: string;
    readonly id: string;
    readonly nexusTrustStoreEnabled: boolean;
    readonly port: number;
    readonly sslOnConnectEnabled: boolean;
    readonly sslServerIdentityCheckEnabled: boolean;
    readonly startTlsEnabled: boolean;
    readonly startTlsRequired: boolean;
    readonly subjectPrefix: string;
    readonly username: string;
}
export function getMailConfigOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMailConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getMailConfig:getMailConfig", {
    }, opts, utilities.getPackage());
}
