// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPrivilegeScript(args: GetPrivilegeScriptArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivilegeScriptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getPrivilegeScript:getPrivilegeScript", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeScript.
 */
export interface GetPrivilegeScriptArgs {
    name: string;
}

/**
 * A collection of values returned by getPrivilegeScript.
 */
export interface GetPrivilegeScriptResult {
    readonly actions: string[];
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly readonly: boolean;
    readonly scriptName: string;
}
export function getPrivilegeScriptOutput(args: GetPrivilegeScriptOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPrivilegeScriptResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getPrivilegeScript:getPrivilegeScript", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeScript.
 */
export interface GetPrivilegeScriptOutputArgs {
    name: pulumi.Input<string>;
}
