// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPrivilegeRepositoryView(args: GetPrivilegeRepositoryViewArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivilegeRepositoryViewResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getPrivilegeRepositoryView:getPrivilegeRepositoryView", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeRepositoryView.
 */
export interface GetPrivilegeRepositoryViewArgs {
    name: string;
}

/**
 * A collection of values returned by getPrivilegeRepositoryView.
 */
export interface GetPrivilegeRepositoryViewResult {
    readonly actions: string[];
    readonly description: string;
    readonly format: string;
    readonly id: string;
    readonly name: string;
    readonly readonly: boolean;
    readonly repository: string;
}
export function getPrivilegeRepositoryViewOutput(args: GetPrivilegeRepositoryViewOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPrivilegeRepositoryViewResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getPrivilegeRepositoryView:getPrivilegeRepositoryView", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeRepositoryView.
 */
export interface GetPrivilegeRepositoryViewOutputArgs {
    name: pulumi.Input<string>;
}
