// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPrivilegeApplication(args: GetPrivilegeApplicationArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivilegeApplicationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getPrivilegeApplication:getPrivilegeApplication", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeApplication.
 */
export interface GetPrivilegeApplicationArgs {
    name: string;
}

/**
 * A collection of values returned by getPrivilegeApplication.
 */
export interface GetPrivilegeApplicationResult {
    readonly actions: string[];
    readonly description: string;
    readonly domain: string;
    readonly id: string;
    readonly name: string;
    readonly readonly: boolean;
}
export function getPrivilegeApplicationOutput(args: GetPrivilegeApplicationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPrivilegeApplicationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getPrivilegeApplication:getPrivilegeApplication", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeApplication.
 */
export interface GetPrivilegeApplicationOutputArgs {
    name: pulumi.Input<string>;
}
