// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPrivilegeWildcard(args: GetPrivilegeWildcardArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivilegeWildcardResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getPrivilegeWildcard:getPrivilegeWildcard", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeWildcard.
 */
export interface GetPrivilegeWildcardArgs {
    name: string;
}

/**
 * A collection of values returned by getPrivilegeWildcard.
 */
export interface GetPrivilegeWildcardResult {
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly pattern: string;
    readonly readonly: boolean;
}
export function getPrivilegeWildcardOutput(args: GetPrivilegeWildcardOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPrivilegeWildcardResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getPrivilegeWildcard:getPrivilegeWildcard", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeWildcard.
 */
export interface GetPrivilegeWildcardOutputArgs {
    name: pulumi.Input<string>;
}
