// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryCargoHosted(args: GetRepositoryCargoHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryCargoHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryCargoHosted:getRepositoryCargoHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCargoHosted.
 */
export interface GetRepositoryCargoHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryCargoHosted.
 */
export interface GetRepositoryCargoHostedResult {
    readonly cleanups: outputs.GetRepositoryCargoHostedCleanup[];
    readonly components: outputs.GetRepositoryCargoHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryCargoHostedStorage[];
}
export function getRepositoryCargoHostedOutput(args: GetRepositoryCargoHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryCargoHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryCargoHosted:getRepositoryCargoHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCargoHosted.
 */
export interface GetRepositoryCargoHostedOutputArgs {
    name: pulumi.Input<string>;
}
