// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryPypiProxy(args: GetRepositoryPypiProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryPypiProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryPypiProxy:getRepositoryPypiProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryPypiProxy.
 */
export interface GetRepositoryPypiProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryPypiProxy.
 */
export interface GetRepositoryPypiProxyResult {
    readonly cleanups: outputs.GetRepositoryPypiProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryPypiProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryPypiProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryPypiProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryPypiProxyStorage[];
}
export function getRepositoryPypiProxyOutput(args: GetRepositoryPypiProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryPypiProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryPypiProxy:getRepositoryPypiProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryPypiProxy.
 */
export interface GetRepositoryPypiProxyOutputArgs {
    name: pulumi.Input<string>;
}
