// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryNugetProxy(args: GetRepositoryNugetProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryNugetProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryNugetProxy:getRepositoryNugetProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNugetProxy.
 */
export interface GetRepositoryNugetProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryNugetProxy.
 */
export interface GetRepositoryNugetProxyResult {
    readonly cleanups: outputs.GetRepositoryNugetProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryNugetProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryNugetProxyNegativeCach[];
    readonly nugetVersion: string;
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryNugetProxyProxy[];
    readonly queryCacheItemMaxAge: number;
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryNugetProxyStorage[];
}
export function getRepositoryNugetProxyOutput(args: GetRepositoryNugetProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryNugetProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryNugetProxy:getRepositoryNugetProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNugetProxy.
 */
export interface GetRepositoryNugetProxyOutputArgs {
    name: pulumi.Input<string>;
}
