// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryBowerProxy(args: GetRepositoryBowerProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryBowerProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryBowerProxy:getRepositoryBowerProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryBowerProxy.
 */
export interface GetRepositoryBowerProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryBowerProxy.
 */
export interface GetRepositoryBowerProxyResult {
    readonly cleanups: outputs.GetRepositoryBowerProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryBowerProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryBowerProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryBowerProxyProxy[];
    readonly rewritePackageUrls: boolean;
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryBowerProxyStorage[];
}
export function getRepositoryBowerProxyOutput(args: GetRepositoryBowerProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryBowerProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryBowerProxy:getRepositoryBowerProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryBowerProxy.
 */
export interface GetRepositoryBowerProxyOutputArgs {
    name: pulumi.Input<string>;
}
