// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryDockerProxy(args: GetRepositoryDockerProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryDockerProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryDockerProxy:getRepositoryDockerProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryDockerProxy.
 */
export interface GetRepositoryDockerProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryDockerProxy.
 */
export interface GetRepositoryDockerProxyResult {
    readonly cleanups: outputs.GetRepositoryDockerProxyCleanup[];
    readonly dockerProxies: outputs.GetRepositoryDockerProxyDockerProxy[];
    readonly dockers: outputs.GetRepositoryDockerProxyDocker[];
    readonly httpClients: outputs.GetRepositoryDockerProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryDockerProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryDockerProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryDockerProxyStorage[];
}
export function getRepositoryDockerProxyOutput(args: GetRepositoryDockerProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryDockerProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryDockerProxy:getRepositoryDockerProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryDockerProxy.
 */
export interface GetRepositoryDockerProxyOutputArgs {
    name: pulumi.Input<string>;
}
