// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryGoGroup(args: GetRepositoryGoGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryGoGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryGoGroup:getRepositoryGoGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryGoGroup.
 */
export interface GetRepositoryGoGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryGoGroup.
 */
export interface GetRepositoryGoGroupResult {
    readonly groups: outputs.GetRepositoryGoGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryGoGroupStorage[];
}
export function getRepositoryGoGroupOutput(args: GetRepositoryGoGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryGoGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryGoGroup:getRepositoryGoGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryGoGroup.
 */
export interface GetRepositoryGoGroupOutputArgs {
    name: pulumi.Input<string>;
}
