// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRoutingRule(args: GetRoutingRuleArgs, opts?: pulumi.InvokeOptions): Promise<GetRoutingRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRoutingRule:getRoutingRule", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRoutingRule.
 */
export interface GetRoutingRuleArgs {
    name: string;
}

/**
 * A collection of values returned by getRoutingRule.
 */
export interface GetRoutingRuleResult {
    readonly description: string;
    readonly id: string;
    readonly matchers: string[];
    readonly mode: string;
    readonly name: string;
}
export function getRoutingRuleOutput(args: GetRoutingRuleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoutingRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRoutingRule:getRoutingRule", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRoutingRule.
 */
export interface GetRoutingRuleOutputArgs {
    name: pulumi.Input<string>;
}
