// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRubygemsProxy(args: GetRepositoryRubygemsProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRubygemsProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRubygemsProxy:getRepositoryRubygemsProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRubygemsProxy.
 */
export interface GetRepositoryRubygemsProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRubygemsProxy.
 */
export interface GetRepositoryRubygemsProxyResult {
    readonly cleanups: outputs.GetRepositoryRubygemsProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryRubygemsProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryRubygemsProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryRubygemsProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryRubygemsProxyStorage[];
}
export function getRepositoryRubygemsProxyOutput(args: GetRepositoryRubygemsProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRubygemsProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRubygemsProxy:getRepositoryRubygemsProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRubygemsProxy.
 */
export interface GetRepositoryRubygemsProxyOutputArgs {
    name: pulumi.Input<string>;
}
