// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryGoProxy(args: GetRepositoryGoProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryGoProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryGoProxy:getRepositoryGoProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryGoProxy.
 */
export interface GetRepositoryGoProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryGoProxy.
 */
export interface GetRepositoryGoProxyResult {
    readonly cleanups: outputs.GetRepositoryGoProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryGoProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryGoProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryGoProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryGoProxyStorage[];
}
export function getRepositoryGoProxyOutput(args: GetRepositoryGoProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryGoProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryGoProxy:getRepositoryGoProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryGoProxy.
 */
export interface GetRepositoryGoProxyOutputArgs {
    name: pulumi.Input<string>;
}
