// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryDockerHosted(args: GetRepositoryDockerHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryDockerHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryDockerHosted:getRepositoryDockerHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryDockerHosted.
 */
export interface GetRepositoryDockerHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryDockerHosted.
 */
export interface GetRepositoryDockerHostedResult {
    readonly cleanups: outputs.GetRepositoryDockerHostedCleanup[];
    readonly components: outputs.GetRepositoryDockerHostedComponent[];
    readonly dockers: outputs.GetRepositoryDockerHostedDocker[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryDockerHostedStorage[];
}
export function getRepositoryDockerHostedOutput(args: GetRepositoryDockerHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryDockerHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryDockerHosted:getRepositoryDockerHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryDockerHosted.
 */
export interface GetRepositoryDockerHostedOutputArgs {
    name: pulumi.Input<string>;
}
