// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryPypiHosted(args: GetRepositoryPypiHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryPypiHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryPypiHosted:getRepositoryPypiHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryPypiHosted.
 */
export interface GetRepositoryPypiHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryPypiHosted.
 */
export interface GetRepositoryPypiHostedResult {
    readonly cleanups: outputs.GetRepositoryPypiHostedCleanup[];
    readonly components: outputs.GetRepositoryPypiHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryPypiHostedStorage[];
}
export function getRepositoryPypiHostedOutput(args: GetRepositoryPypiHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryPypiHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryPypiHosted:getRepositoryPypiHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryPypiHosted.
 */
export interface GetRepositoryPypiHostedOutputArgs {
    name: pulumi.Input<string>;
}
