// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryNpmGroup(args: GetRepositoryNpmGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryNpmGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryNpmGroup:getRepositoryNpmGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNpmGroup.
 */
export interface GetRepositoryNpmGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryNpmGroup.
 */
export interface GetRepositoryNpmGroupResult {
    readonly groups: outputs.GetRepositoryNpmGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryNpmGroupStorage[];
}
export function getRepositoryNpmGroupOutput(args: GetRepositoryNpmGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryNpmGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryNpmGroup:getRepositoryNpmGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNpmGroup.
 */
export interface GetRepositoryNpmGroupOutputArgs {
    name: pulumi.Input<string>;
}
