// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryGitlfsHosted(args: GetRepositoryGitlfsHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryGitlfsHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryGitlfsHosted:getRepositoryGitlfsHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryGitlfsHosted.
 */
export interface GetRepositoryGitlfsHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryGitlfsHosted.
 */
export interface GetRepositoryGitlfsHostedResult {
    readonly cleanups: outputs.GetRepositoryGitlfsHostedCleanup[];
    readonly components: outputs.GetRepositoryGitlfsHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryGitlfsHostedStorage[];
}
export function getRepositoryGitlfsHostedOutput(args: GetRepositoryGitlfsHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryGitlfsHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryGitlfsHosted:getRepositoryGitlfsHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryGitlfsHosted.
 */
export interface GetRepositoryGitlfsHostedOutputArgs {
    name: pulumi.Input<string>;
}
