// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryYumGroup(args: GetRepositoryYumGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryYumGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryYumGroup:getRepositoryYumGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryYumGroup.
 */
export interface GetRepositoryYumGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryYumGroup.
 */
export interface GetRepositoryYumGroupResult {
    readonly groups: outputs.GetRepositoryYumGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryYumGroupStorage[];
    readonly yumSignings: outputs.GetRepositoryYumGroupYumSigning[];
}
export function getRepositoryYumGroupOutput(args: GetRepositoryYumGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryYumGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryYumGroup:getRepositoryYumGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryYumGroup.
 */
export interface GetRepositoryYumGroupOutputArgs {
    name: pulumi.Input<string>;
}
