// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRGroup(args: GetRepositoryRGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRGroup:getRepositoryRGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRGroup.
 */
export interface GetRepositoryRGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRGroup.
 */
export interface GetRepositoryRGroupResult {
    readonly groups: outputs.GetRepositoryRGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryRGroupStorage[];
}
export function getRepositoryRGroupOutput(args: GetRepositoryRGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRGroup:getRepositoryRGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRGroup.
 */
export interface GetRepositoryRGroupOutputArgs {
    name: pulumi.Input<string>;
}
