// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryMavenGroup(args: GetRepositoryMavenGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryMavenGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryMavenGroup:getRepositoryMavenGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryMavenGroup.
 */
export interface GetRepositoryMavenGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryMavenGroup.
 */
export interface GetRepositoryMavenGroupResult {
    readonly groups: outputs.GetRepositoryMavenGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryMavenGroupStorage[];
}
export function getRepositoryMavenGroupOutput(args: GetRepositoryMavenGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryMavenGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryMavenGroup:getRepositoryMavenGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryMavenGroup.
 */
export interface GetRepositoryMavenGroupOutputArgs {
    name: pulumi.Input<string>;
}
