// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryNpmHosted(args: GetRepositoryNpmHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryNpmHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryNpmHosted:getRepositoryNpmHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNpmHosted.
 */
export interface GetRepositoryNpmHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryNpmHosted.
 */
export interface GetRepositoryNpmHostedResult {
    readonly cleanups: outputs.GetRepositoryNpmHostedCleanup[];
    readonly components: outputs.GetRepositoryNpmHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryNpmHostedStorage[];
}
export function getRepositoryNpmHostedOutput(args: GetRepositoryNpmHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryNpmHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryNpmHosted:getRepositoryNpmHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNpmHosted.
 */
export interface GetRepositoryNpmHostedOutputArgs {
    name: pulumi.Input<string>;
}
