// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRubygemsHosted(args: GetRepositoryRubygemsHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRubygemsHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRubygemsHosted:getRepositoryRubygemsHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRubygemsHosted.
 */
export interface GetRepositoryRubygemsHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRubygemsHosted.
 */
export interface GetRepositoryRubygemsHostedResult {
    readonly cleanups: outputs.GetRepositoryRubygemsHostedCleanup[];
    readonly components: outputs.GetRepositoryRubygemsHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryRubygemsHostedStorage[];
}
export function getRepositoryRubygemsHostedOutput(args: GetRepositoryRubygemsHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRubygemsHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRubygemsHosted:getRepositoryRubygemsHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRubygemsHosted.
 */
export interface GetRepositoryRubygemsHostedOutputArgs {
    name: pulumi.Input<string>;
}
