// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRawProxy(args: GetRepositoryRawProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRawProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRawProxy:getRepositoryRawProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRawProxy.
 */
export interface GetRepositoryRawProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRawProxy.
 */
export interface GetRepositoryRawProxyResult {
    readonly cleanups: outputs.GetRepositoryRawProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryRawProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryRawProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryRawProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryRawProxyStorage[];
}
export function getRepositoryRawProxyOutput(args: GetRepositoryRawProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRawProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRawProxy:getRepositoryRawProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRawProxy.
 */
export interface GetRepositoryRawProxyOutputArgs {
    name: pulumi.Input<string>;
}
