// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryCocoapodsProxy(args: GetRepositoryCocoapodsProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryCocoapodsProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryCocoapodsProxy:getRepositoryCocoapodsProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCocoapodsProxy.
 */
export interface GetRepositoryCocoapodsProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryCocoapodsProxy.
 */
export interface GetRepositoryCocoapodsProxyResult {
    readonly cleanups: outputs.GetRepositoryCocoapodsProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryCocoapodsProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryCocoapodsProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryCocoapodsProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryCocoapodsProxyStorage[];
}
export function getRepositoryCocoapodsProxyOutput(args: GetRepositoryCocoapodsProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryCocoapodsProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryCocoapodsProxy:getRepositoryCocoapodsProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCocoapodsProxy.
 */
export interface GetRepositoryCocoapodsProxyOutputArgs {
    name: pulumi.Input<string>;
}
