// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryCargoGroup(args: GetRepositoryCargoGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryCargoGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryCargoGroup:getRepositoryCargoGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCargoGroup.
 */
export interface GetRepositoryCargoGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryCargoGroup.
 */
export interface GetRepositoryCargoGroupResult {
    readonly groups: outputs.GetRepositoryCargoGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryCargoGroupStorage[];
}
export function getRepositoryCargoGroupOutput(args: GetRepositoryCargoGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryCargoGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryCargoGroup:getRepositoryCargoGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCargoGroup.
 */
export interface GetRepositoryCargoGroupOutputArgs {
    name: pulumi.Input<string>;
}
