// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRawHosted(args: GetRepositoryRawHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRawHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRawHosted:getRepositoryRawHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRawHosted.
 */
export interface GetRepositoryRawHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRawHosted.
 */
export interface GetRepositoryRawHostedResult {
    readonly cleanups: outputs.GetRepositoryRawHostedCleanup[];
    readonly components: outputs.GetRepositoryRawHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryRawHostedStorage[];
}
export function getRepositoryRawHostedOutput(args: GetRepositoryRawHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRawHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRawHosted:getRepositoryRawHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRawHosted.
 */
export interface GetRepositoryRawHostedOutputArgs {
    name: pulumi.Input<string>;
}
