// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryMavenHosted(args: GetRepositoryMavenHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryMavenHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryMavenHosted:getRepositoryMavenHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryMavenHosted.
 */
export interface GetRepositoryMavenHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryMavenHosted.
 */
export interface GetRepositoryMavenHostedResult {
    readonly cleanups: outputs.GetRepositoryMavenHostedCleanup[];
    readonly components: outputs.GetRepositoryMavenHostedComponent[];
    readonly id: string;
    readonly mavens: outputs.GetRepositoryMavenHostedMaven[];
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryMavenHostedStorage[];
}
export function getRepositoryMavenHostedOutput(args: GetRepositoryMavenHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryMavenHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryMavenHosted:getRepositoryMavenHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryMavenHosted.
 */
export interface GetRepositoryMavenHostedOutputArgs {
    name: pulumi.Input<string>;
}
