// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRProxy(args: GetRepositoryRProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRProxy:getRepositoryRProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRProxy.
 */
export interface GetRepositoryRProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRProxy.
 */
export interface GetRepositoryRProxyResult {
    readonly cleanups: outputs.GetRepositoryRProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryRProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryRProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryRProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryRProxyStorage[];
}
export function getRepositoryRProxyOutput(args: GetRepositoryRProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRProxy:getRepositoryRProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRProxy.
 */
export interface GetRepositoryRProxyOutputArgs {
    name: pulumi.Input<string>;
}
