// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryAptHosted(args: GetRepositoryAptHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryAptHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryAptHosted:getRepositoryAptHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryAptHosted.
 */
export interface GetRepositoryAptHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryAptHosted.
 */
export interface GetRepositoryAptHostedResult {
    readonly cleanups: outputs.GetRepositoryAptHostedCleanup[];
    readonly components: outputs.GetRepositoryAptHostedComponent[];
    readonly distribution: string;
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly signings: outputs.GetRepositoryAptHostedSigning[];
    readonly storages: outputs.GetRepositoryAptHostedStorage[];
}
export function getRepositoryAptHostedOutput(args: GetRepositoryAptHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryAptHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryAptHosted:getRepositoryAptHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryAptHosted.
 */
export interface GetRepositoryAptHostedOutputArgs {
    name: pulumi.Input<string>;
}
