// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryCondaProxy(args: GetRepositoryCondaProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryCondaProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryCondaProxy:getRepositoryCondaProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCondaProxy.
 */
export interface GetRepositoryCondaProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryCondaProxy.
 */
export interface GetRepositoryCondaProxyResult {
    readonly cleanups: outputs.GetRepositoryCondaProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryCondaProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryCondaProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryCondaProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryCondaProxyStorage[];
}
export function getRepositoryCondaProxyOutput(args: GetRepositoryCondaProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryCondaProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryCondaProxy:getRepositoryCondaProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCondaProxy.
 */
export interface GetRepositoryCondaProxyOutputArgs {
    name: pulumi.Input<string>;
}
