// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryAptProxy(args: GetRepositoryAptProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryAptProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryAptProxy:getRepositoryAptProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryAptProxy.
 */
export interface GetRepositoryAptProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryAptProxy.
 */
export interface GetRepositoryAptProxyResult {
    readonly cleanups: outputs.GetRepositoryAptProxyCleanup[];
    readonly distribution: string;
    readonly flat: boolean;
    readonly httpClients: outputs.GetRepositoryAptProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryAptProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryAptProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryAptProxyStorage[];
}
export function getRepositoryAptProxyOutput(args: GetRepositoryAptProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryAptProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryAptProxy:getRepositoryAptProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryAptProxy.
 */
export interface GetRepositoryAptProxyOutputArgs {
    name: pulumi.Input<string>;
}
