// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryNugetHosted(args: GetRepositoryNugetHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryNugetHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryNugetHosted:getRepositoryNugetHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNugetHosted.
 */
export interface GetRepositoryNugetHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryNugetHosted.
 */
export interface GetRepositoryNugetHostedResult {
    readonly cleanups: outputs.GetRepositoryNugetHostedCleanup[];
    readonly components: outputs.GetRepositoryNugetHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryNugetHostedStorage[];
}
export function getRepositoryNugetHostedOutput(args: GetRepositoryNugetHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryNugetHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryNugetHosted:getRepositoryNugetHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNugetHosted.
 */
export interface GetRepositoryNugetHostedOutputArgs {
    name: pulumi.Input<string>;
}
