// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryList(opts?: pulumi.InvokeOptions): Promise<GetRepositoryListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryList:getRepositoryList", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getRepositoryList.
 */
export interface GetRepositoryListResult {
    readonly id: string;
    readonly items: outputs.GetRepositoryListItem[];
}
export function getRepositoryListOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryList:getRepositoryList", {
    }, opts, utilities.getPackage());
}
