// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecurityUserToken(opts?: pulumi.InvokeOptions): Promise<GetSecurityUserTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecurityUserToken:getSecurityUserToken", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSecurityUserToken.
 */
export interface GetSecurityUserTokenResult {
    readonly enabled: boolean;
    readonly expirationDays: number;
    readonly expirationEnabled: boolean;
    readonly id: string;
    readonly protectContent: boolean;
}
export function getSecurityUserTokenOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityUserTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecurityUserToken:getSecurityUserToken", {
    }, opts, utilities.getPackage());
}
