// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSecurityRealms(opts?: pulumi.InvokeOptions): Promise<GetSecurityRealmsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecurityRealms:getSecurityRealms", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSecurityRealms.
 */
export interface GetSecurityRealmsResult {
    readonly actives: outputs.GetSecurityRealmsActive[];
    readonly availables: outputs.GetSecurityRealmsAvailable[];
    readonly id: string;
}
export function getSecurityRealmsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityRealmsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecurityRealms:getSecurityRealms", {
    }, opts, utilities.getPackage());
}
