// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSecuritySslTruststore(opts?: pulumi.InvokeOptions): Promise<GetSecuritySslTruststoreResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecuritySslTruststore:getSecuritySslTruststore", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSecuritySslTruststore.
 */
export interface GetSecuritySslTruststoreResult {
    readonly certificates: outputs.GetSecuritySslTruststoreCertificate[];
    readonly id: string;
}
export function getSecuritySslTruststoreOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecuritySslTruststoreResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecuritySslTruststore:getSecuritySslTruststore", {
    }, opts, utilities.getPackage());
}
