// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecuritySsl(args: GetSecuritySslArgs, opts?: pulumi.InvokeOptions): Promise<GetSecuritySslResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecuritySsl:getSecuritySsl", {
        "host": args.host,
        "port": args.port,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecuritySsl.
 */
export interface GetSecuritySslArgs {
    host: string;
    port?: number;
}

/**
 * A collection of values returned by getSecuritySsl.
 */
export interface GetSecuritySslResult {
    readonly expiresOn: number;
    readonly fingerprint: string;
    readonly host: string;
    readonly id: string;
    readonly issuedOn: number;
    readonly issuerCommonName: string;
    readonly issuerOrganization: string;
    readonly issuerOrganizationUnit: string;
    readonly pem: string;
    readonly port?: number;
    readonly serialNumber: string;
    readonly subjectCommonName: string;
    readonly subjectOrganization: string;
    readonly subjectOrganizationUnit: string;
}
export function getSecuritySslOutput(args: GetSecuritySslOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecuritySslResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecuritySsl:getSecuritySsl", {
        "host": args.host,
        "port": args.port,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecuritySsl.
 */
export interface GetSecuritySslOutputArgs {
    host: pulumi.Input<string>;
    port?: pulumi.Input<number>;
}
