// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSecurityLdap(opts?: pulumi.InvokeOptions): Promise<GetSecurityLdapResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecurityLdap:getSecurityLdap", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSecurityLdap.
 */
export interface GetSecurityLdapResult {
    readonly id: string;
    readonly ldaps: outputs.GetSecurityLdapLdap[];
}
export function getSecurityLdapOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityLdapResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecurityLdap:getSecurityLdap", {
    }, opts, utilities.getPackage());
}
