// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecuritySaml(opts?: pulumi.InvokeOptions): Promise<GetSecuritySamlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecuritySaml:getSecuritySaml", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSecuritySaml.
 */
export interface GetSecuritySamlResult {
    readonly emailAttribute: string;
    readonly entityId: string;
    readonly firstNameAttribute: string;
    readonly groupsAttribute: string;
    readonly id: string;
    readonly idpMetadata: string;
    readonly lastNameAttribute: string;
    readonly usernameAttribute: string;
    readonly validateAssertionSignature: boolean;
    readonly validateResponseSignature: boolean;
}
export function getSecuritySamlOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecuritySamlResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecuritySaml:getSecuritySaml", {
    }, opts, utilities.getPackage());
}
