// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecurityAnonymous(opts?: pulumi.InvokeOptions): Promise<GetSecurityAnonymousResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecurityAnonymous:getSecurityAnonymous", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getSecurityAnonymous.
 */
export interface GetSecurityAnonymousResult {
    readonly enabled: boolean;
    readonly id: string;
    readonly realmName: string;
    readonly userId: string;
}
export function getSecurityAnonymousOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityAnonymousResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecurityAnonymous:getSecurityAnonymous", {
    }, opts, utilities.getPackage());
}
