// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecurityContentSelector(args: GetSecurityContentSelectorArgs, opts?: pulumi.InvokeOptions): Promise<GetSecurityContentSelectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecurityContentSelector:getSecurityContentSelector", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecurityContentSelector.
 */
export interface GetSecurityContentSelectorArgs {
    name: string;
}

/**
 * A collection of values returned by getSecurityContentSelector.
 */
export interface GetSecurityContentSelectorResult {
    readonly description: string;
    readonly expression: string;
    readonly id: string;
    readonly name: string;
}
export function getSecurityContentSelectorOutput(args: GetSecurityContentSelectorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityContentSelectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecurityContentSelector:getSecurityContentSelector", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecurityContentSelector.
 */
export interface GetSecurityContentSelectorOutputArgs {
    name: pulumi.Input<string>;
}
