// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PrivilegeRepositoryView extends pulumi.CustomResource {
    /**
     * Get an existing PrivilegeRepositoryView resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PrivilegeRepositoryViewState, opts?: pulumi.CustomResourceOptions): PrivilegeRepositoryView {
        return new PrivilegeRepositoryView(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/privilegeRepositoryView:PrivilegeRepositoryView';

    /**
     * Returns true if the given object is an instance of PrivilegeRepositoryView.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PrivilegeRepositoryView {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PrivilegeRepositoryView.__pulumiType;
    }

    /**
     * A list of allowed actions. For a list of applicable values see
     * https://help.sonatype.com/repomanager3/nexus-repository-administration/access-control/privileges#Privileges-PrivilegeTypes
     */
    public readonly actions!: pulumi.Output<string[]>;
    /**
     * A description
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The format of the referenced Repository
     */
    public readonly format!: pulumi.Output<string>;
    /**
     * The name of the privilege. This value cannot be changed.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Name of the repository the privilege applies to
     */
    public readonly repository!: pulumi.Output<string>;

    /**
     * Create a PrivilegeRepositoryView resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PrivilegeRepositoryViewArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PrivilegeRepositoryViewArgs | PrivilegeRepositoryViewState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PrivilegeRepositoryViewState | undefined;
            resourceInputs["actions"] = state ? state.actions : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["format"] = state ? state.format : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["repository"] = state ? state.repository : undefined;
        } else {
            const args = argsOrState as PrivilegeRepositoryViewArgs | undefined;
            if ((!args || args.actions === undefined) && !opts.urn) {
                throw new Error("Missing required property 'actions'");
            }
            if ((!args || args.format === undefined) && !opts.urn) {
                throw new Error("Missing required property 'format'");
            }
            if ((!args || args.repository === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["actions"] = args ? args.actions : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["format"] = args ? args.format : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["repository"] = args ? args.repository : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PrivilegeRepositoryView.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PrivilegeRepositoryView resources.
 */
export interface PrivilegeRepositoryViewState {
    /**
     * A list of allowed actions. For a list of applicable values see
     * https://help.sonatype.com/repomanager3/nexus-repository-administration/access-control/privileges#Privileges-PrivilegeTypes
     */
    actions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A description
     */
    description?: pulumi.Input<string>;
    /**
     * The format of the referenced Repository
     */
    format?: pulumi.Input<string>;
    /**
     * The name of the privilege. This value cannot be changed.
     */
    name?: pulumi.Input<string>;
    /**
     * Name of the repository the privilege applies to
     */
    repository?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PrivilegeRepositoryView resource.
 */
export interface PrivilegeRepositoryViewArgs {
    /**
     * A list of allowed actions. For a list of applicable values see
     * https://help.sonatype.com/repomanager3/nexus-repository-administration/access-control/privileges#Privileges-PrivilegeTypes
     */
    actions: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A description
     */
    description?: pulumi.Input<string>;
    /**
     * The format of the referenced Repository
     */
    format: pulumi.Input<string>;
    /**
     * The name of the privilege. This value cannot be changed.
     */
    name?: pulumi.Input<string>;
    /**
     * Name of the repository the privilege applies to
     */
    repository: pulumi.Input<string>;
}
