// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RepositoryConanProxy extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryConanProxy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryConanProxyState, opts?: pulumi.CustomResourceOptions): RepositoryConanProxy {
        return new RepositoryConanProxy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/repositoryConanProxy:RepositoryConanProxy';

    /**
     * Returns true if the given object is an instance of RepositoryConanProxy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryConanProxy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryConanProxy.__pulumiType;
    }

    /**
     * Cleanup policies
     */
    public readonly cleanups!: pulumi.Output<outputs.RepositoryConanProxyCleanup[] | undefined>;
    /**
     * HTTP Client configuration for proxy repositories
     */
    public readonly httpClient!: pulumi.Output<outputs.RepositoryConanProxyHttpClient>;
    /**
     * A unique identifier for this repository
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Configuration of the negative cache handling
     */
    public readonly negativeCache!: pulumi.Output<outputs.RepositoryConanProxyNegativeCache>;
    /**
     * Whether this repository accepts incoming requests
     */
    public readonly online!: pulumi.Output<boolean | undefined>;
    /**
     * Configuration for the proxy repository
     */
    public readonly proxy!: pulumi.Output<outputs.RepositoryConanProxyProxy>;
    /**
     * The name of the routing rule assigned to this repository
     */
    public readonly routingRule!: pulumi.Output<string | undefined>;
    /**
     * The storage configuration of the repository
     */
    public readonly storage!: pulumi.Output<outputs.RepositoryConanProxyStorage>;

    /**
     * Create a RepositoryConanProxy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryConanProxyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryConanProxyArgs | RepositoryConanProxyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryConanProxyState | undefined;
            resourceInputs["cleanups"] = state ? state.cleanups : undefined;
            resourceInputs["httpClient"] = state ? state.httpClient : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["negativeCache"] = state ? state.negativeCache : undefined;
            resourceInputs["online"] = state ? state.online : undefined;
            resourceInputs["proxy"] = state ? state.proxy : undefined;
            resourceInputs["routingRule"] = state ? state.routingRule : undefined;
            resourceInputs["storage"] = state ? state.storage : undefined;
        } else {
            const args = argsOrState as RepositoryConanProxyArgs | undefined;
            if ((!args || args.httpClient === undefined) && !opts.urn) {
                throw new Error("Missing required property 'httpClient'");
            }
            if ((!args || args.negativeCache === undefined) && !opts.urn) {
                throw new Error("Missing required property 'negativeCache'");
            }
            if ((!args || args.proxy === undefined) && !opts.urn) {
                throw new Error("Missing required property 'proxy'");
            }
            if ((!args || args.storage === undefined) && !opts.urn) {
                throw new Error("Missing required property 'storage'");
            }
            resourceInputs["cleanups"] = args ? args.cleanups : undefined;
            resourceInputs["httpClient"] = args ? args.httpClient : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["negativeCache"] = args ? args.negativeCache : undefined;
            resourceInputs["online"] = args ? args.online : undefined;
            resourceInputs["proxy"] = args ? args.proxy : undefined;
            resourceInputs["routingRule"] = args ? args.routingRule : undefined;
            resourceInputs["storage"] = args ? args.storage : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryConanProxy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryConanProxy resources.
 */
export interface RepositoryConanProxyState {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryConanProxyCleanup>[]>;
    /**
     * HTTP Client configuration for proxy repositories
     */
    httpClient?: pulumi.Input<inputs.RepositoryConanProxyHttpClient>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Configuration of the negative cache handling
     */
    negativeCache?: pulumi.Input<inputs.RepositoryConanProxyNegativeCache>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * Configuration for the proxy repository
     */
    proxy?: pulumi.Input<inputs.RepositoryConanProxyProxy>;
    /**
     * The name of the routing rule assigned to this repository
     */
    routingRule?: pulumi.Input<string>;
    /**
     * The storage configuration of the repository
     */
    storage?: pulumi.Input<inputs.RepositoryConanProxyStorage>;
}

/**
 * The set of arguments for constructing a RepositoryConanProxy resource.
 */
export interface RepositoryConanProxyArgs {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryConanProxyCleanup>[]>;
    /**
     * HTTP Client configuration for proxy repositories
     */
    httpClient: pulumi.Input<inputs.RepositoryConanProxyHttpClient>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Configuration of the negative cache handling
     */
    negativeCache: pulumi.Input<inputs.RepositoryConanProxyNegativeCache>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * Configuration for the proxy repository
     */
    proxy: pulumi.Input<inputs.RepositoryConanProxyProxy>;
    /**
     * The name of the routing rule assigned to this repository
     */
    routingRule?: pulumi.Input<string>;
    /**
     * The storage configuration of the repository
     */
    storage: pulumi.Input<inputs.RepositoryConanProxyStorage>;
}
