// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RepositoryYumHosted extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryYumHosted resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryYumHostedState, opts?: pulumi.CustomResourceOptions): RepositoryYumHosted {
        return new RepositoryYumHosted(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/repositoryYumHosted:RepositoryYumHosted';

    /**
     * Returns true if the given object is an instance of RepositoryYumHosted.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryYumHosted {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryYumHosted.__pulumiType;
    }

    /**
     * Cleanup policies
     */
    public readonly cleanups!: pulumi.Output<outputs.RepositoryYumHostedCleanup[] | undefined>;
    /**
     * Component configuration for the hosted repository
     */
    public readonly component!: pulumi.Output<outputs.RepositoryYumHostedComponent | undefined>;
    /**
     * Validate that all paths are RPMs or yum metadata. Possible values: `STRICT` or `PERMISSIVE`
     */
    public readonly deployPolicy!: pulumi.Output<string | undefined>;
    /**
     * A unique identifier for this repository
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    public readonly online!: pulumi.Output<boolean | undefined>;
    /**
     * Specifies the repository depth where repodata folder(s) are created. Possible values: 0-5
     */
    public readonly repodataDepth!: pulumi.Output<number | undefined>;
    /**
     * The storage configuration of the repository
     */
    public readonly storage!: pulumi.Output<outputs.RepositoryYumHostedStorage>;

    /**
     * Create a RepositoryYumHosted resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryYumHostedArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryYumHostedArgs | RepositoryYumHostedState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryYumHostedState | undefined;
            resourceInputs["cleanups"] = state ? state.cleanups : undefined;
            resourceInputs["component"] = state ? state.component : undefined;
            resourceInputs["deployPolicy"] = state ? state.deployPolicy : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["online"] = state ? state.online : undefined;
            resourceInputs["repodataDepth"] = state ? state.repodataDepth : undefined;
            resourceInputs["storage"] = state ? state.storage : undefined;
        } else {
            const args = argsOrState as RepositoryYumHostedArgs | undefined;
            if ((!args || args.storage === undefined) && !opts.urn) {
                throw new Error("Missing required property 'storage'");
            }
            resourceInputs["cleanups"] = args ? args.cleanups : undefined;
            resourceInputs["component"] = args ? args.component : undefined;
            resourceInputs["deployPolicy"] = args ? args.deployPolicy : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["online"] = args ? args.online : undefined;
            resourceInputs["repodataDepth"] = args ? args.repodataDepth : undefined;
            resourceInputs["storage"] = args ? args.storage : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryYumHosted.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryYumHosted resources.
 */
export interface RepositoryYumHostedState {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryYumHostedCleanup>[]>;
    /**
     * Component configuration for the hosted repository
     */
    component?: pulumi.Input<inputs.RepositoryYumHostedComponent>;
    /**
     * Validate that all paths are RPMs or yum metadata. Possible values: `STRICT` or `PERMISSIVE`
     */
    deployPolicy?: pulumi.Input<string>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * Specifies the repository depth where repodata folder(s) are created. Possible values: 0-5
     */
    repodataDepth?: pulumi.Input<number>;
    /**
     * The storage configuration of the repository
     */
    storage?: pulumi.Input<inputs.RepositoryYumHostedStorage>;
}

/**
 * The set of arguments for constructing a RepositoryYumHosted resource.
 */
export interface RepositoryYumHostedArgs {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryYumHostedCleanup>[]>;
    /**
     * Component configuration for the hosted repository
     */
    component?: pulumi.Input<inputs.RepositoryYumHostedComponent>;
    /**
     * Validate that all paths are RPMs or yum metadata. Possible values: `STRICT` or `PERMISSIVE`
     */
    deployPolicy?: pulumi.Input<string>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * Specifies the repository depth where repodata folder(s) are created. Possible values: 0-5
     */
    repodataDepth?: pulumi.Input<number>;
    /**
     * The storage configuration of the repository
     */
    storage: pulumi.Input<inputs.RepositoryYumHostedStorage>;
}
