// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RepositoryMavenHosted extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryMavenHosted resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryMavenHostedState, opts?: pulumi.CustomResourceOptions): RepositoryMavenHosted {
        return new RepositoryMavenHosted(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/repositoryMavenHosted:RepositoryMavenHosted';

    /**
     * Returns true if the given object is an instance of RepositoryMavenHosted.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryMavenHosted {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryMavenHosted.__pulumiType;
    }

    /**
     * Cleanup policies
     */
    public readonly cleanups!: pulumi.Output<outputs.RepositoryMavenHostedCleanup[] | undefined>;
    /**
     * Component configuration for the hosted repository
     */
    public readonly component!: pulumi.Output<outputs.RepositoryMavenHostedComponent | undefined>;
    /**
     * Maven contains additional data of maven repository
     */
    public readonly maven!: pulumi.Output<outputs.RepositoryMavenHostedMaven>;
    /**
     * A unique identifier for this repository
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    public readonly online!: pulumi.Output<boolean | undefined>;
    /**
     * The storage configuration of the repository
     */
    public readonly storage!: pulumi.Output<outputs.RepositoryMavenHostedStorage>;

    /**
     * Create a RepositoryMavenHosted resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryMavenHostedArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryMavenHostedArgs | RepositoryMavenHostedState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryMavenHostedState | undefined;
            resourceInputs["cleanups"] = state ? state.cleanups : undefined;
            resourceInputs["component"] = state ? state.component : undefined;
            resourceInputs["maven"] = state ? state.maven : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["online"] = state ? state.online : undefined;
            resourceInputs["storage"] = state ? state.storage : undefined;
        } else {
            const args = argsOrState as RepositoryMavenHostedArgs | undefined;
            if ((!args || args.maven === undefined) && !opts.urn) {
                throw new Error("Missing required property 'maven'");
            }
            if ((!args || args.storage === undefined) && !opts.urn) {
                throw new Error("Missing required property 'storage'");
            }
            resourceInputs["cleanups"] = args ? args.cleanups : undefined;
            resourceInputs["component"] = args ? args.component : undefined;
            resourceInputs["maven"] = args ? args.maven : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["online"] = args ? args.online : undefined;
            resourceInputs["storage"] = args ? args.storage : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryMavenHosted.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryMavenHosted resources.
 */
export interface RepositoryMavenHostedState {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryMavenHostedCleanup>[]>;
    /**
     * Component configuration for the hosted repository
     */
    component?: pulumi.Input<inputs.RepositoryMavenHostedComponent>;
    /**
     * Maven contains additional data of maven repository
     */
    maven?: pulumi.Input<inputs.RepositoryMavenHostedMaven>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * The storage configuration of the repository
     */
    storage?: pulumi.Input<inputs.RepositoryMavenHostedStorage>;
}

/**
 * The set of arguments for constructing a RepositoryMavenHosted resource.
 */
export interface RepositoryMavenHostedArgs {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryMavenHostedCleanup>[]>;
    /**
     * Component configuration for the hosted repository
     */
    component?: pulumi.Input<inputs.RepositoryMavenHostedComponent>;
    /**
     * Maven contains additional data of maven repository
     */
    maven: pulumi.Input<inputs.RepositoryMavenHostedMaven>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * The storage configuration of the repository
     */
    storage: pulumi.Input<inputs.RepositoryMavenHostedStorage>;
}
