// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RepositoryNugetProxy extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryNugetProxy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryNugetProxyState, opts?: pulumi.CustomResourceOptions): RepositoryNugetProxy {
        return new RepositoryNugetProxy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/repositoryNugetProxy:RepositoryNugetProxy';

    /**
     * Returns true if the given object is an instance of RepositoryNugetProxy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryNugetProxy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryNugetProxy.__pulumiType;
    }

    /**
     * Cleanup policies
     */
    public readonly cleanups!: pulumi.Output<outputs.RepositoryNugetProxyCleanup[] | undefined>;
    /**
     * HTTP Client configuration for proxy repositories
     */
    public readonly httpClient!: pulumi.Output<outputs.RepositoryNugetProxyHttpClient>;
    /**
     * A unique identifier for this repository
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Configuration of the negative cache handling
     */
    public readonly negativeCache!: pulumi.Output<outputs.RepositoryNugetProxyNegativeCache>;
    /**
     * Nuget protocol version
     */
    public readonly nugetVersion!: pulumi.Output<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    public readonly online!: pulumi.Output<boolean | undefined>;
    /**
     * Configuration for the proxy repository
     */
    public readonly proxy!: pulumi.Output<outputs.RepositoryNugetProxyProxy>;
    /**
     * How long to cache query results from the proxied repository (in seconds)
     */
    public readonly queryCacheItemMaxAge!: pulumi.Output<number>;
    /**
     * The name of the routing rule assigned to this repository
     */
    public readonly routingRule!: pulumi.Output<string | undefined>;
    /**
     * The storage configuration of the repository
     */
    public readonly storage!: pulumi.Output<outputs.RepositoryNugetProxyStorage>;

    /**
     * Create a RepositoryNugetProxy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryNugetProxyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryNugetProxyArgs | RepositoryNugetProxyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryNugetProxyState | undefined;
            resourceInputs["cleanups"] = state ? state.cleanups : undefined;
            resourceInputs["httpClient"] = state ? state.httpClient : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["negativeCache"] = state ? state.negativeCache : undefined;
            resourceInputs["nugetVersion"] = state ? state.nugetVersion : undefined;
            resourceInputs["online"] = state ? state.online : undefined;
            resourceInputs["proxy"] = state ? state.proxy : undefined;
            resourceInputs["queryCacheItemMaxAge"] = state ? state.queryCacheItemMaxAge : undefined;
            resourceInputs["routingRule"] = state ? state.routingRule : undefined;
            resourceInputs["storage"] = state ? state.storage : undefined;
        } else {
            const args = argsOrState as RepositoryNugetProxyArgs | undefined;
            if ((!args || args.httpClient === undefined) && !opts.urn) {
                throw new Error("Missing required property 'httpClient'");
            }
            if ((!args || args.negativeCache === undefined) && !opts.urn) {
                throw new Error("Missing required property 'negativeCache'");
            }
            if ((!args || args.nugetVersion === undefined) && !opts.urn) {
                throw new Error("Missing required property 'nugetVersion'");
            }
            if ((!args || args.proxy === undefined) && !opts.urn) {
                throw new Error("Missing required property 'proxy'");
            }
            if ((!args || args.queryCacheItemMaxAge === undefined) && !opts.urn) {
                throw new Error("Missing required property 'queryCacheItemMaxAge'");
            }
            if ((!args || args.storage === undefined) && !opts.urn) {
                throw new Error("Missing required property 'storage'");
            }
            resourceInputs["cleanups"] = args ? args.cleanups : undefined;
            resourceInputs["httpClient"] = args ? args.httpClient : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["negativeCache"] = args ? args.negativeCache : undefined;
            resourceInputs["nugetVersion"] = args ? args.nugetVersion : undefined;
            resourceInputs["online"] = args ? args.online : undefined;
            resourceInputs["proxy"] = args ? args.proxy : undefined;
            resourceInputs["queryCacheItemMaxAge"] = args ? args.queryCacheItemMaxAge : undefined;
            resourceInputs["routingRule"] = args ? args.routingRule : undefined;
            resourceInputs["storage"] = args ? args.storage : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryNugetProxy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RepositoryNugetProxy resources.
 */
export interface RepositoryNugetProxyState {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryNugetProxyCleanup>[]>;
    /**
     * HTTP Client configuration for proxy repositories
     */
    httpClient?: pulumi.Input<inputs.RepositoryNugetProxyHttpClient>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Configuration of the negative cache handling
     */
    negativeCache?: pulumi.Input<inputs.RepositoryNugetProxyNegativeCache>;
    /**
     * Nuget protocol version
     */
    nugetVersion?: pulumi.Input<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * Configuration for the proxy repository
     */
    proxy?: pulumi.Input<inputs.RepositoryNugetProxyProxy>;
    /**
     * How long to cache query results from the proxied repository (in seconds)
     */
    queryCacheItemMaxAge?: pulumi.Input<number>;
    /**
     * The name of the routing rule assigned to this repository
     */
    routingRule?: pulumi.Input<string>;
    /**
     * The storage configuration of the repository
     */
    storage?: pulumi.Input<inputs.RepositoryNugetProxyStorage>;
}

/**
 * The set of arguments for constructing a RepositoryNugetProxy resource.
 */
export interface RepositoryNugetProxyArgs {
    /**
     * Cleanup policies
     */
    cleanups?: pulumi.Input<pulumi.Input<inputs.RepositoryNugetProxyCleanup>[]>;
    /**
     * HTTP Client configuration for proxy repositories
     */
    httpClient: pulumi.Input<inputs.RepositoryNugetProxyHttpClient>;
    /**
     * A unique identifier for this repository
     */
    name?: pulumi.Input<string>;
    /**
     * Configuration of the negative cache handling
     */
    negativeCache: pulumi.Input<inputs.RepositoryNugetProxyNegativeCache>;
    /**
     * Nuget protocol version
     */
    nugetVersion: pulumi.Input<string>;
    /**
     * Whether this repository accepts incoming requests
     */
    online?: pulumi.Input<boolean>;
    /**
     * Configuration for the proxy repository
     */
    proxy: pulumi.Input<inputs.RepositoryNugetProxyProxy>;
    /**
     * How long to cache query results from the proxied repository (in seconds)
     */
    queryCacheItemMaxAge: pulumi.Input<number>;
    /**
     * The name of the routing rule assigned to this repository
     */
    routingRule?: pulumi.Input<string>;
    /**
     * The storage configuration of the repository
     */
    storage: pulumi.Input<inputs.RepositoryNugetProxyStorage>;
}
