// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecurityUserToken extends pulumi.CustomResource {
    /**
     * Get an existing SecurityUserToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecurityUserTokenState, opts?: pulumi.CustomResourceOptions): SecurityUserToken {
        return new SecurityUserToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/securityUserToken:SecurityUserToken';

    /**
     * Returns true if the given object is an instance of SecurityUserToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityUserToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityUserToken.__pulumiType;
    }

    /**
     * Activate the feature of user tokens.
     */
    public readonly enabled!: pulumi.Output<boolean>;
    /**
     * Number of days for which you want user tokens to remain valid.
     */
    public readonly expirationDays!: pulumi.Output<number | undefined>;
    /**
     * Set user tokens expiration.
     */
    public readonly expirationEnabled!: pulumi.Output<boolean | undefined>;
    /**
     * Require user tokens for repository authentication. This does not effect UI access.
     */
    public readonly protectContent!: pulumi.Output<boolean | undefined>;

    /**
     * Create a SecurityUserToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecurityUserTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecurityUserTokenArgs | SecurityUserTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecurityUserTokenState | undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["expirationDays"] = state ? state.expirationDays : undefined;
            resourceInputs["expirationEnabled"] = state ? state.expirationEnabled : undefined;
            resourceInputs["protectContent"] = state ? state.protectContent : undefined;
        } else {
            const args = argsOrState as SecurityUserTokenArgs | undefined;
            if ((!args || args.enabled === undefined) && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["expirationDays"] = args ? args.expirationDays : undefined;
            resourceInputs["expirationEnabled"] = args ? args.expirationEnabled : undefined;
            resourceInputs["protectContent"] = args ? args.protectContent : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecurityUserToken.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SecurityUserToken resources.
 */
export interface SecurityUserTokenState {
    /**
     * Activate the feature of user tokens.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Number of days for which you want user tokens to remain valid.
     */
    expirationDays?: pulumi.Input<number>;
    /**
     * Set user tokens expiration.
     */
    expirationEnabled?: pulumi.Input<boolean>;
    /**
     * Require user tokens for repository authentication. This does not effect UI access.
     */
    protectContent?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a SecurityUserToken resource.
 */
export interface SecurityUserTokenArgs {
    /**
     * Activate the feature of user tokens.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * Number of days for which you want user tokens to remain valid.
     */
    expirationDays?: pulumi.Input<number>;
    /**
     * Set user tokens expiration.
     */
    expirationEnabled?: pulumi.Input<boolean>;
    /**
     * Require user tokens for repository authentication. This does not effect UI access.
     */
    protectContent?: pulumi.Input<boolean>;
}
