// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecuritySslTruststore extends pulumi.CustomResource {
    /**
     * Get an existing SecuritySslTruststore resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecuritySslTruststoreState, opts?: pulumi.CustomResourceOptions): SecuritySslTruststore {
        return new SecuritySslTruststore(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/securitySslTruststore:SecuritySslTruststore';

    /**
     * Returns true if the given object is an instance of SecuritySslTruststore.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecuritySslTruststore {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecuritySslTruststore.__pulumiType;
    }

    /**
     * The fingerprint of the cert
     */
    public /*out*/ readonly fingerprint!: pulumi.Output<string>;
    /**
     * The cert in PEM format
     */
    public readonly pem!: pulumi.Output<string>;

    /**
     * Create a SecuritySslTruststore resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecuritySslTruststoreArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecuritySslTruststoreArgs | SecuritySslTruststoreState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecuritySslTruststoreState | undefined;
            resourceInputs["fingerprint"] = state ? state.fingerprint : undefined;
            resourceInputs["pem"] = state ? state.pem : undefined;
        } else {
            const args = argsOrState as SecuritySslTruststoreArgs | undefined;
            if ((!args || args.pem === undefined) && !opts.urn) {
                throw new Error("Missing required property 'pem'");
            }
            resourceInputs["pem"] = args ? args.pem : undefined;
            resourceInputs["fingerprint"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecuritySslTruststore.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SecuritySslTruststore resources.
 */
export interface SecuritySslTruststoreState {
    /**
     * The fingerprint of the cert
     */
    fingerprint?: pulumi.Input<string>;
    /**
     * The cert in PEM format
     */
    pem?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SecuritySslTruststore resource.
 */
export interface SecuritySslTruststoreArgs {
    /**
     * The cert in PEM format
     */
    pem: pulumi.Input<string>;
}
