// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("nexus");

/**
 * Path to a client PEM certificate to load for mTLS. Reading environment variable NEXUS_CLIENT_CERT_PATH. Default:``
 */
export declare const clientCertPath: string | undefined;
Object.defineProperty(exports, "clientCertPath", {
    get() {
        return __config.get("clientCertPath");
    },
    enumerable: true,
});

/**
 * Path to a client PEM key to load for mTLS. Reading environment variable NEXUS_CLIENT_KEY_PATH. Default:``
 */
export declare const clientKeyPath: string | undefined;
Object.defineProperty(exports, "clientKeyPath", {
    get() {
        return __config.get("clientKeyPath");
    },
    enumerable: true,
});

/**
 * Boolean to specify wether insecure SSL connections are allowed or not. Reading environment variable
 * NEXUS_INSECURE_SKIP_VERIFY. Default:`true`
 */
export declare const insecure: boolean | undefined;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure");
    },
    enumerable: true,
});

/**
 * Password of user to connect to API. Reading environment variable NEXUS_PASSWORD. Default:`admin123`
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * Path to a root CA certificate to load for mTLS. Reading environment variable NEXUS_ROOT_CA_PATH. Default:``
 */
export declare const rootCaPath: string | undefined;
Object.defineProperty(exports, "rootCaPath", {
    get() {
        return __config.get("rootCaPath");
    },
    enumerable: true,
});

/**
 * Timeout in seconds to connect to API. Reading environment variable NEXUS_TIMEOUT. Default:`30`
 */
export declare const timeout: number | undefined;
Object.defineProperty(exports, "timeout", {
    get() {
        return __config.getObject<number>("timeout");
    },
    enumerable: true,
});

/**
 * URL of Nexus to reach API. Reading environment variable NEXUS_URL. Default:`http://127.0.0.1:8080`
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

/**
 * Username used to connect to API. Reading environment variable NEXUS_USERNAME. Default:`admin`
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

