// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPrivilegeRepositoryAdmin(args: GetPrivilegeRepositoryAdminArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivilegeRepositoryAdminResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getPrivilegeRepositoryAdmin:getPrivilegeRepositoryAdmin", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeRepositoryAdmin.
 */
export interface GetPrivilegeRepositoryAdminArgs {
    name: string;
}

/**
 * A collection of values returned by getPrivilegeRepositoryAdmin.
 */
export interface GetPrivilegeRepositoryAdminResult {
    readonly actions: string[];
    readonly description: string;
    readonly format: string;
    readonly id: string;
    readonly name: string;
    readonly readonly: boolean;
    readonly repository: string;
}
export function getPrivilegeRepositoryAdminOutput(args: GetPrivilegeRepositoryAdminOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPrivilegeRepositoryAdminResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getPrivilegeRepositoryAdmin:getPrivilegeRepositoryAdmin", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPrivilegeRepositoryAdmin.
 */
export interface GetPrivilegeRepositoryAdminOutputArgs {
    name: pulumi.Input<string>;
}
