// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryMavenProxy(args: GetRepositoryMavenProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryMavenProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryMavenProxy:getRepositoryMavenProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryMavenProxy.
 */
export interface GetRepositoryMavenProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryMavenProxy.
 */
export interface GetRepositoryMavenProxyResult {
    readonly cleanups: outputs.GetRepositoryMavenProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryMavenProxyHttpClient[];
    readonly id: string;
    readonly mavens: outputs.GetRepositoryMavenProxyMaven[];
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryMavenProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryMavenProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryMavenProxyStorage[];
}
export function getRepositoryMavenProxyOutput(args: GetRepositoryMavenProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryMavenProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryMavenProxy:getRepositoryMavenProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryMavenProxy.
 */
export interface GetRepositoryMavenProxyOutputArgs {
    name: pulumi.Input<string>;
}
