// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryHelmHosted(args: GetRepositoryHelmHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryHelmHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryHelmHosted:getRepositoryHelmHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryHelmHosted.
 */
export interface GetRepositoryHelmHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryHelmHosted.
 */
export interface GetRepositoryHelmHostedResult {
    readonly cleanups: outputs.GetRepositoryHelmHostedCleanup[];
    readonly components: outputs.GetRepositoryHelmHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryHelmHostedStorage[];
}
export function getRepositoryHelmHostedOutput(args: GetRepositoryHelmHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryHelmHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryHelmHosted:getRepositoryHelmHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryHelmHosted.
 */
export interface GetRepositoryHelmHostedOutputArgs {
    name: pulumi.Input<string>;
}
