// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryBowerHosted(args: GetRepositoryBowerHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryBowerHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryBowerHosted:getRepositoryBowerHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryBowerHosted.
 */
export interface GetRepositoryBowerHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryBowerHosted.
 */
export interface GetRepositoryBowerHostedResult {
    readonly cleanups: outputs.GetRepositoryBowerHostedCleanup[];
    readonly components: outputs.GetRepositoryBowerHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryBowerHostedStorage[];
}
export function getRepositoryBowerHostedOutput(args: GetRepositoryBowerHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryBowerHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryBowerHosted:getRepositoryBowerHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryBowerHosted.
 */
export interface GetRepositoryBowerHostedOutputArgs {
    name: pulumi.Input<string>;
}
