// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryHelmProxy(args: GetRepositoryHelmProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryHelmProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryHelmProxy:getRepositoryHelmProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryHelmProxy.
 */
export interface GetRepositoryHelmProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryHelmProxy.
 */
export interface GetRepositoryHelmProxyResult {
    readonly cleanups: outputs.GetRepositoryHelmProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryHelmProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryHelmProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryHelmProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryHelmProxyStorage[];
}
export function getRepositoryHelmProxyOutput(args: GetRepositoryHelmProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryHelmProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryHelmProxy:getRepositoryHelmProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryHelmProxy.
 */
export interface GetRepositoryHelmProxyOutputArgs {
    name: pulumi.Input<string>;
}
