// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryDockerGroup(args: GetRepositoryDockerGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryDockerGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryDockerGroup:getRepositoryDockerGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryDockerGroup.
 */
export interface GetRepositoryDockerGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryDockerGroup.
 */
export interface GetRepositoryDockerGroupResult {
    readonly dockers: outputs.GetRepositoryDockerGroupDocker[];
    readonly groups: outputs.GetRepositoryDockerGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryDockerGroupStorage[];
}
export function getRepositoryDockerGroupOutput(args: GetRepositoryDockerGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryDockerGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryDockerGroup:getRepositoryDockerGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryDockerGroup.
 */
export interface GetRepositoryDockerGroupOutputArgs {
    name: pulumi.Input<string>;
}
