// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryPypiGroup(args: GetRepositoryPypiGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryPypiGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryPypiGroup:getRepositoryPypiGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryPypiGroup.
 */
export interface GetRepositoryPypiGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryPypiGroup.
 */
export interface GetRepositoryPypiGroupResult {
    readonly groups: outputs.GetRepositoryPypiGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryPypiGroupStorage[];
}
export function getRepositoryPypiGroupOutput(args: GetRepositoryPypiGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryPypiGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryPypiGroup:getRepositoryPypiGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryPypiGroup.
 */
export interface GetRepositoryPypiGroupOutputArgs {
    name: pulumi.Input<string>;
}
