// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryNpmProxy(args: GetRepositoryNpmProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryNpmProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryNpmProxy:getRepositoryNpmProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNpmProxy.
 */
export interface GetRepositoryNpmProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryNpmProxy.
 */
export interface GetRepositoryNpmProxyResult {
    readonly cleanups: outputs.GetRepositoryNpmProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryNpmProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryNpmProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryNpmProxyProxy[];
    /**
     * @deprecated Deprecated
     */
    readonly removeNonCataloged: boolean;
    readonly removeQuarantined: boolean;
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryNpmProxyStorage[];
}
export function getRepositoryNpmProxyOutput(args: GetRepositoryNpmProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryNpmProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryNpmProxy:getRepositoryNpmProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryNpmProxy.
 */
export interface GetRepositoryNpmProxyOutputArgs {
    name: pulumi.Input<string>;
}
