// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryYumProxy(args: GetRepositoryYumProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryYumProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryYumProxy:getRepositoryYumProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryYumProxy.
 */
export interface GetRepositoryYumProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryYumProxy.
 */
export interface GetRepositoryYumProxyResult {
    readonly cleanups: outputs.GetRepositoryYumProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryYumProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryYumProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryYumProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryYumProxyStorage[];
    readonly yumSignings: outputs.GetRepositoryYumProxyYumSigning[];
}
export function getRepositoryYumProxyOutput(args: GetRepositoryYumProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryYumProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryYumProxy:getRepositoryYumProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryYumProxy.
 */
export interface GetRepositoryYumProxyOutputArgs {
    name: pulumi.Input<string>;
}
