// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRHosted(args: GetRepositoryRHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRHosted:getRepositoryRHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRHosted.
 */
export interface GetRepositoryRHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRHosted.
 */
export interface GetRepositoryRHostedResult {
    readonly cleanups: outputs.GetRepositoryRHostedCleanup[];
    readonly components: outputs.GetRepositoryRHostedComponent[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryRHostedStorage[];
}
export function getRepositoryRHostedOutput(args: GetRepositoryRHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRHosted:getRepositoryRHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRHosted.
 */
export interface GetRepositoryRHostedOutputArgs {
    name: pulumi.Input<string>;
}
