// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryYumHosted(args: GetRepositoryYumHostedArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryYumHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryYumHosted:getRepositoryYumHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryYumHosted.
 */
export interface GetRepositoryYumHostedArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryYumHosted.
 */
export interface GetRepositoryYumHostedResult {
    readonly cleanups: outputs.GetRepositoryYumHostedCleanup[];
    readonly components: outputs.GetRepositoryYumHostedComponent[];
    readonly deployPolicy: string;
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly repodataDepth: number;
    readonly storages: outputs.GetRepositoryYumHostedStorage[];
}
export function getRepositoryYumHostedOutput(args: GetRepositoryYumHostedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryYumHostedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryYumHosted:getRepositoryYumHosted", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryYumHosted.
 */
export interface GetRepositoryYumHostedOutputArgs {
    name: pulumi.Input<string>;
}
