// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryCargoProxy(args: GetRepositoryCargoProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryCargoProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryCargoProxy:getRepositoryCargoProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCargoProxy.
 */
export interface GetRepositoryCargoProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryCargoProxy.
 */
export interface GetRepositoryCargoProxyResult {
    readonly cargoVersion: string;
    readonly cleanups: outputs.GetRepositoryCargoProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryCargoProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryCargoProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryCargoProxyProxy[];
    readonly queryCacheItemMaxAge: number;
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryCargoProxyStorage[];
}
export function getRepositoryCargoProxyOutput(args: GetRepositoryCargoProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryCargoProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryCargoProxy:getRepositoryCargoProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryCargoProxy.
 */
export interface GetRepositoryCargoProxyOutputArgs {
    name: pulumi.Input<string>;
}
