// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryConanProxy(args: GetRepositoryConanProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryConanProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryConanProxy:getRepositoryConanProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryConanProxy.
 */
export interface GetRepositoryConanProxyArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryConanProxy.
 */
export interface GetRepositoryConanProxyResult {
    readonly cleanups: outputs.GetRepositoryConanProxyCleanup[];
    readonly httpClients: outputs.GetRepositoryConanProxyHttpClient[];
    readonly id: string;
    readonly name: string;
    readonly negativeCaches: outputs.GetRepositoryConanProxyNegativeCach[];
    readonly online: boolean;
    readonly proxies: outputs.GetRepositoryConanProxyProxy[];
    readonly routingRule: string;
    readonly storages: outputs.GetRepositoryConanProxyStorage[];
}
export function getRepositoryConanProxyOutput(args: GetRepositoryConanProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryConanProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryConanProxy:getRepositoryConanProxy", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryConanProxy.
 */
export interface GetRepositoryConanProxyOutputArgs {
    name: pulumi.Input<string>;
}
