// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRubygemsGroup(args: GetRepositoryRubygemsGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRubygemsGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRubygemsGroup:getRepositoryRubygemsGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRubygemsGroup.
 */
export interface GetRepositoryRubygemsGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRubygemsGroup.
 */
export interface GetRepositoryRubygemsGroupResult {
    readonly groups: outputs.GetRepositoryRubygemsGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryRubygemsGroupStorage[];
}
export function getRepositoryRubygemsGroupOutput(args: GetRepositoryRubygemsGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRubygemsGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRubygemsGroup:getRepositoryRubygemsGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRubygemsGroup.
 */
export interface GetRepositoryRubygemsGroupOutputArgs {
    name: pulumi.Input<string>;
}
