// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepositoryRawGroup(args: GetRepositoryRawGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryRawGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getRepositoryRawGroup:getRepositoryRawGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRawGroup.
 */
export interface GetRepositoryRawGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getRepositoryRawGroup.
 */
export interface GetRepositoryRawGroupResult {
    readonly groups: outputs.GetRepositoryRawGroupGroup[];
    readonly id: string;
    readonly name: string;
    readonly online: boolean;
    readonly storages: outputs.GetRepositoryRawGroupStorage[];
}
export function getRepositoryRawGroupOutput(args: GetRepositoryRawGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryRawGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getRepositoryRawGroup:getRepositoryRawGroup", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepositoryRawGroup.
 */
export interface GetRepositoryRawGroupOutputArgs {
    name: pulumi.Input<string>;
}
