// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSecurityUser(args: GetSecurityUserArgs, opts?: pulumi.InvokeOptions): Promise<GetSecurityUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nexus:index/getSecurityUser:getSecurityUser", {
        "userid": args.userid,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecurityUser.
 */
export interface GetSecurityUserArgs {
    userid: string;
}

/**
 * A collection of values returned by getSecurityUser.
 */
export interface GetSecurityUserResult {
    readonly email: string;
    readonly firstname: string;
    readonly id: string;
    readonly lastname: string;
    readonly roles: string[];
    readonly status: string;
    readonly userid: string;
}
export function getSecurityUserOutput(args: GetSecurityUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecurityUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("nexus:index/getSecurityUser:getSecurityUser", {
        "userid": args.userid,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSecurityUser.
 */
export interface GetSecurityUserOutputArgs {
    userid: pulumi.Input<string>;
}
