// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecurityRole extends pulumi.CustomResource {
    /**
     * Get an existing SecurityRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecurityRoleState, opts?: pulumi.CustomResourceOptions): SecurityRole {
        return new SecurityRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nexus:index/securityRole:SecurityRole';

    /**
     * Returns true if the given object is an instance of SecurityRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityRole.__pulumiType;
    }

    /**
     * The description of this role.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The name of the role.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The privileges of this role.
     */
    public readonly privileges!: pulumi.Output<string[] | undefined>;
    /**
     * The id of the role.
     */
    public readonly roleid!: pulumi.Output<string>;
    /**
     * The roles of this role.
     */
    public readonly roles!: pulumi.Output<string[] | undefined>;

    /**
     * Create a SecurityRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecurityRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecurityRoleArgs | SecurityRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecurityRoleState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["privileges"] = state ? state.privileges : undefined;
            resourceInputs["roleid"] = state ? state.roleid : undefined;
            resourceInputs["roles"] = state ? state.roles : undefined;
        } else {
            const args = argsOrState as SecurityRoleArgs | undefined;
            if ((!args || args.roleid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roleid'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["privileges"] = args ? args.privileges : undefined;
            resourceInputs["roleid"] = args ? args.roleid : undefined;
            resourceInputs["roles"] = args ? args.roles : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecurityRole.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SecurityRole resources.
 */
export interface SecurityRoleState {
    /**
     * The description of this role.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the role.
     */
    name?: pulumi.Input<string>;
    /**
     * The privileges of this role.
     */
    privileges?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The id of the role.
     */
    roleid?: pulumi.Input<string>;
    /**
     * The roles of this role.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a SecurityRole resource.
 */
export interface SecurityRoleArgs {
    /**
     * The description of this role.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the role.
     */
    name?: pulumi.Input<string>;
    /**
     * The privileges of this role.
     */
    privileges?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The id of the role.
     */
    roleid: pulumi.Input<string>;
    /**
     * The roles of this role.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
}
